export enum ERROR_TYPE {
    USER_IS_EXIT="USER_IS_EXIT",
    USER_IS_NOT_EXIT="USER_IS_NOT_EXIT",
    MANGA_NOT_FOUND="MANGA_NOT_FOUND",
    POST_NOT_FOUND="POST_NOT_FOUND",
    COMMENT_NOT_FOUND="COMMENT_NOT_FOUND",
    YOU_NOT_PERMISSiON="YOU_NOT_PERMISSION",
    PASSWORD_IS_CORRECT="PASSWORD_IS_CORRECT",
    USER_NOT_FOUND="USER_NOT_FOUND",
    TOKEN_IS_CORRECT="TOKEN_IS_CORRECT",
    CHAPTER_NOT_FOUND="CHAPTER_NOT_FOUND",
    ERROR_SYSTEM="ERROR_SYSTEM",
    EMAIL_IS_EXITS="EMAIL_IS_EXITS",
    EMAIL_OR_PASSWORD_IS_CORRECT="EMAIL_OR_PASSWORD_IS_CORRECT",
    COMMENT_NOT_FOUND_OR_DELETED="COMMENT_NOT_FOUND_OR_DELETED",
    PLEASE_LOGIN_USER="PLEASE_LOGIN_USER"
}
